version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-server
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root123
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
